### ISSUE TITLE
선택된 카테고리에도 표시가 되었으면 좋겠습니다.

### ISSUE THREAD

**Issue by hannut91** [CodeSoom-Project/coffee-and-taste#1]
카테고리에 마우스를 가져다 대면 표시가되는데, 선택된 것은 표시가 안되는 것 같네요.
선택된 카테고리가 무엇인지도 표시가 되면 좋겠습니다.

<img width="531" alt="image" src="https://user-images.githubusercontent.com/14071105/174729212-40429b0a-dbb1-4e55-912a-eef98a90e7dc.png">

**Comment by hdpyo** [comment]
## 작업 내역
- 카테고리를 클릭하면 클릭한 카테고리 밑에 녹색 밑줄이 추가되도록 수정했습니다.
- PR : #8 

---

## 추가 작업 : 리팩토링

### 기존 작업에서 수정/추가한 점
- 기존 작업은 별도의 useState 를 사용했으나,  이미 사용중인 리덕스의 selectedCategory 상태값을 이용해 
같은 기능을 더 간결한 코드로 적용할 수 있었습니다.
- 기존에는 카테고리를 클릭한 선택된 카테고리에 스타일은 잘 적용됐으나, 
'로고'를 클릭하면 해당 스타일이 사리지지 않고 그대로 남아있어서 버그처럼 동작했습니다.
따라서 '로고'를 클릭했을 때 selectedCategory 상태값을 0으로 초기화하도록 수정하였습니다.

- PR : #10
