### ISSUE TITLE
새로고침했을 때 404를 보여줍니다.

### ISSUE THREAD

**Issue by hannut91** [CodeSoom-Project/coffee-and-taste#2]
카테고리를 클릭하고 새로고침을 하면 404를 보여줍니다. 404가 보여지 않도록 해주세요.

<img width="589" alt="image" src="https://user-images.githubusercontent.com/14071105/174731035-2690bca9-95a5-495e-a7ca-3f256893c64d.png">

**Comment by hdpyo** [comment]
### 원인
- Github Pages 는 SPA 를 지원하지 않는다고 합니다.
따라서 `https://[도메인]/main` 과 같은 URL 을 인식하지 못하고 404 page 를 호출합니다.

### 해결 방법
- 프로젝트 빌드 시 index.html 을 404.html 로 복사하도록 package.json 을 수정하여 해결하였습니다.

  * Pull Request 내역 : [페이지 새로고침 시 404 에러가 발생하는 오류 수정 #6](https://github.com/CodeSoom-Project/coffee-and-taste/pull/6)

### 참고
* 위 방법은 gh-pages 에서 사용하는 편법?과 같은 방법인 것으로 보입니다.

**Comment by hannut91** [comment]
좋습니다!
