### ISSUE TITLE
구조분해 할당을 사용해서 더 간단하게 표현해 보세요

### ISSUE THREAD

**Issue by hannut91** [CodeSoom-Project/coffee-and-taste#3]
https://github.com/CodeSoom-Project/coffee-and-taste/blob/fb4c5ff13da627f646e18827817b585572e01887/src/MenuGroup.jsx#L50

**Comment by hdpyo** [comment]
## 작업 내역
- 기존 코드에서 디스트럭처링을 이용해 코드를 간결하게 작성할 수 있는  컴포넌트들을 모두 수정하였습니다.
- PR : #9
